let five_line_tracker = emakefun.createFiveLineTracker(80)
five_line_tracker.setSensitivity(500)
basic.forever(function() {
  serial.writeString('digital values:')
  serial.writeNumber(five_line_tracker.digitalValue(0))
  serial.writeString(', ')
  serial.writeNumber(five_line_tracker.digitalValue(1))
  serial.writeString(', ')
  serial.writeNumber(five_line_tracker.digitalValue(2))
  serial.writeString(', ')
  serial.writeNumber(five_line_tracker.digitalValue(3))
  serial.writeString(', ')
  serial.writeNumber(five_line_tracker.digitalValue(4))
  serial.writeString(', analog values:')
  serial.writeNumber(five_line_tracker.analogValue(0))
  serial.writeString(', ')
  serial.writeNumber(five_line_tracker.analogValue(1))
  serial.writeString(', ')
  serial.writeNumber(five_line_tracker.analogValue(2))
  serial.writeString(', ')
  serial.writeNumber(five_line_tracker.analogValue(3))
  serial.writeString(', ')
  serial.writeNumber(five_line_tracker.analogValue(4))
  serial.writeLine('')
  basic.pause(100)
})
